### ISSUE TITLE
commit_id is not part of the pull request

### ISSUE THREAD

**Issue by spajus** [mmozuras/pronto#109]
When running Pronto via Jenkins with github_pr formatter, I often get this:

```
/var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/<org>/<repo>/pulls/355/comments: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: PullRequestReviewComment
  code: custom
  field: commit_id
  message: commit_id is not part of the pull request // See: https://developer.github.com/v3/pulls/comments/#create-a-comment
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/connection.rb:154:in `request'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/connection.rb:28:in `post'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/octokit-4.1.1/lib/octokit/client/pull_requests.rb:211:in `create_pull_request_comment'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/github.rb:31:in `create_pull_comment'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/formatter/github_pull_request_formatter.rb:33:in `create_comment'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/formatter/github_pull_request_formatter.rb:21:in `block in format'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/formatter/github_pull_request_formatter.rb:8:in `map'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/formatter/github_pull_request_formatter.rb:8:in `format'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto.rb:37:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/lib/pronto/cli.rb:52:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.3/bin/pronto:6:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/bin/pronto:23:in `load'
	from /var/lib/jenkins/.rbenv/versions/2.1.5/bin/pronto:23:in `<main>'
```

**Comment by mmozuras** [comment]
@spajus what version of Pronto are you running?

**Comment by spajus** [comment]
@mmozuras 

```
pronto (0.4.3)
    pronto-flay (0.4.2)
      pronto (~> 0.4.0)
    pronto-jshint (0.4.2)
      pronto (~> 0.4.0)
    pronto-rails_best_practices (0.4.0)
      pronto (~> 0.4.0)
    pronto-rubocop (0.4.7)
      pronto (~> 0.4.0)
    pronto-scss (0.4.7)
      pronto (~> 0.4.0)
```

**Comment by mmozuras** [comment]
@spajus could you try `0.5.2`? 

https://github.com/mmozuras/pronto/issues/99

**Comment by mmozuras** [comment]
@spajus  when running from forks, also add:

```yml
github:
  slug: your/repo
```

to `.pronto.yml` or `GITHUB_SLUG` env var. I'm still trying to figure out how document it best, make this scenario work better.

**Comment by spajus** [comment]
@mmozuras `your/repo` being main upstream?

**Comment by mmozuras** [comment]
@spajus most of the time, yes. Aka the one that you have Pull Requests created on.

**Comment by spajus** [comment]
@mmozuras after adding GITHUB_SLUG and upgrading to 0.5.2 I get many new errors:

```
Failed to post: #<struct Pronto::Github::Comment sha="793bc6de630de25f451682658e1ae7c6ea6c2dab", body="Similar code found in client_spec.rb:187, client_spec.rb:213", path="spec/models/client_spec.rb", position=4> with POST https://api.github.com/repos/<org>/<repo>/pulls/356/comments: 422 - Validation Failed
Error summary:
  resource: PullRequestReviewComment
  code: invalid
  field: path // See: https://developer.github.com/v3/pulls/comments/#create-a-comment
```

It also seems that it was trying to add comments on code that is not related to pull request.

**Comment by mmozuras** [comment]
@spajus hm, ok. Could you give me a description on how to reproduce this?

**Comment by spajus** [comment]
@mmozuras good question... my setup:

- Rails project on github, one "upstream" and several people working with forks and making PRs to that upstream repo.
- Jenkins with GHPRB plugin building pull requests (recent versions, usually up to date)
- Running `RAILS_ENV=test bundle exec pronto run -f github_pr -c origin/master` on those pull requests

I just noticed that wiping out jenkins workspace fixed the issue, at least temporarliy. Comments are successfully added after that. Will wait for it to break again.

**Comment by spajus** [comment]
Well, a working workaround for this issue is to have "Delete workspace before build starts" enabled in your jenkins job. Otherwise something like force pushing or rebasing kills pronto.

**Comment by mmozuras** [comment]
@spajus weird. I'm not intimately familiar with Jenkins workspaces (or your setup, obviously). Are there any actions with `git` repo that are not performed, when workspace is not deleted? Could `git` repo be out of sync when workspace is not deleted?

**Comment by spajus** [comment]
@mmozuras yes, it could be that GitHub Pull Request Builder Jenkins plugin does something messy with git if workspace is kept for long enough, while wiping out workspace does a fresh git clone on each build.

**Comment by mmozuras** [comment]
@spajus marking it as `wontfix` then :smile:
