### ISSUE TITLE
500 error on Gitlab.com

### ISSUE THREAD

**Issue by Fodoj** [mmozuras/pronto#160]
When I am using pronto inside gitlab ci on gitlab.com I get this:

```
$ bundle exec pronto run -f gitlab
/home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/request.rb:72:in `validate': Server responded with code 500, message: . Request URI: https://gitlab.com/api/v3/projects/FJCorp%2Fmkdev.app/repository/commits/01bf6d7fe56edfe1f04a8cef3733a315ceef0b03/comments (Gitlab::Error::InternalServerError)
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/request.rb:41:in `get'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/client/repositories.rb:111:in `commit_comments'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/gitlab.rb:11:in `commit_comments'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/formatter/gitlab_formatter.rb:22:in `create_comment'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/formatter/gitlab_formatter.rb:8:in `block in format'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/formatter/gitlab_formatter.rb:7:in `map'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/formatter/gitlab_formatter.rb:7:in `format'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto.rb:41:in `run'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/lib/pronto/cli.rb:52:in `run'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pronto-0.5.3/bin/pronto:6:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.2.3/bin/pronto:23:in `load'
	from /home/vagrant/.rbenv/versions/2.2.3/bin/pronto:23:in `<main>'
```

**Comment by nbekirov** [comment]
Is is possible that this is related to #146?

**Comment by mmozuras** [comment]
`v3/projects/FJCorp%2Fmkdev.app/repository/commits/`

@Fodoj looking at the provided stacktrace, what @nbekirov wrote is likely correct. You should specify project id instead of project slug in your configuration 😄
