### ISSUE TITLE
Pronto `after_success` step fails

### ISSUE THREAD

**Issue by mknapik** [mmozuras/pronto#163]
Have a look at the bottom of https://travis-ci.org/mmozuras/pronto/jobs/139025270 log.

```
    bundle exec pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
    
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/base.rb:534:in `is_thor_reserved_word?': "run" is a Thor reserved word and cannot be defined as command (RuntimeError)
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/base.rb:597:in `method_added'
	from /home/travis/build/mmozuras/pronto/lib/pronto/cli.rb:44:in `<class:CLI>'
	from /home/travis/build/mmozuras/pronto/lib/pronto/cli.rb:4:in `<module:Pronto>'
	from /home/travis/build/mmozuras/pronto/lib/pronto/cli.rb:3:in `<top (required)>'
	from /home/travis/build/mmozuras/pronto/bin/pronto:4:in `require'
	from /home/travis/build/mmozuras/pronto/bin/pronto:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/pronto:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/pronto:23:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

Recently added configuration for running pronto for pronto project itself seems to stopped working.

**Comment by mmozuras** [comment]
Figured it out 😄  
It's specific only to this particular PR. Reverting [this change](https://github.com/mmozuras/pronto/pull/154#discussion_r69393838) should make it work again.

@mknapik thanks for creating the issue 🙇
