### ISSUE TITLE
pronto integration with teamcity

### ISSUE THREAD

**Issue by mpluta-airhelp** [mmozuras/pronto#168]
Hello,
I have been wondering if anybody got similar problem when working with TC server. We are automatically building PR friom GH (https://blog.jetbrains.com/teamcity/2013/02/automatically-building-pull-requests-from-github-with-teamcity/). I specify `+:refs/pull/(*/merge)` in branch specification. And this creates sth called detached branch like this (note - this maybe not a full instruction):
```
[Updating sources] VCS Root: ah-flights-logger (7s)
[13:57:34][VCS Root: ah-flights-logger] revision: 6f8c020730e17f1cf52a70dee9c8547887c73f42
[13:57:34][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git show-ref
[13:57:34][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git ls-remote origin
[13:57:36][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git show-ref refs/heads/master
[13:57:36][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git show-ref refs/pull/9/merge
[13:57:36][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git fetch --progress origin +refs/pull/9/merge:refs/pull/9/merge (1s)
[13:57:38][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git log -n1 --pretty=format:%H%x20%s 6f8c020730e17f1cf52a70dee9c8547887c73f42 --
[13:57:38][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git config remote.origin.url
[13:57:38][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/system/git/git-C03074D4.git]: /usr/bin/git pack-refs
[13:57:38][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git show-ref
[13:57:38][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git ls-remote origin
[13:57:40][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git show-ref refs/remotes/origin/pull/9/merge
[13:57:40][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git log -n1 --pretty=format:%H%x20%s 6f8c020730e17f1cf52a70dee9c8547887c73f42 --
[13:57:40][VCS Root: ah-flights-logger] Commit '6f8c020730e17f1cf52a70dee9c8547887c73f42' is not found in repository. Running 'git fetch'...
[13:57:40][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git fetch --progress origin refs/pull/9/merge (1s)
[13:57:41][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git log -n1 --pretty=format:%H%x20%s 6f8c020730e17f1cf52a70dee9c8547887c73f42 --
[13:57:41][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git config core.autocrlf
[13:57:41][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git checkout -q -f 6f8c020730e17f1cf52a70dee9c8547887c73f42
[13:57:41][VCS Root: ah-flights-logger] Cleaning ah-flights-logger in /opt/teamcity/TeamCity/buildAgent/work/509933754420bea0 the file set ALL_UNTRACKED
[13:57:41][VCS Root: ah-flights-logger] [/opt/teamcity/TeamCity/buildAgent/work/509933754420bea0]: /usr/bin/git clean -f -d -x

```
Now running pronto on such branch equals getting following error:
```
/usr/local/bundle/gems/pronto-0.6.0/lib/pronto/git/repository.rb:76:in `target': Object not found - no match for id (2f78ae08fccdded7b2a2cdff4ec3a65a96f04b73) (Rugged::OdbError)
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/lib/pronto/git/repository.rb:76:in `head'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/lib/pronto/git/repository.rb:72:in `merge_base'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/lib/pronto/git/repository.rb:15:in `diff'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/lib/pronto.rb:40:in `run'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
[13:57:52][Step 9/10] 	from /usr/local/bundle/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
[13:57:52][Step 9/10] 	from /usr/local/bundle/bin/pronto:22:in `load'
[13:57:52][Step 9/10] 	from /usr/local/bundle/bin/pronto:22:in `<main>'
```
Locally it works fine. Any ideas how to work with detached branches like this?

Regards
MP

**Comment by mpluta-airhelp** [comment]
I managed to create a workaround build step like this:

```
#!/bin/bash -x

PRID=$(expr "%teamcity.build.branch%" : '\([0-9]*\)\/merge')
if [ -z "$PRID" ]
then
  exit 0
fi

git fetch --all
COMMIT=$(git log -n 2 --right-only --pretty='%H' | tail -1)
git branch -a --contains $COMMIT
BRANCH=$(git branch -a --contains $COMMIT | grep 'remotes/' | head -1| sed 's#.*/##g')
rm -rf ./*
git clone -b $BRANCH git@github.com:AirHelp/%PROJECT_NAME%.git
cd %PROJECT_NAME%
GITHUB_ACCESS_TOKEN=%env.GITHUB_ACCESS_TOKEN% PULL_REQUEST_ID=$PRID docker-compose run pronto
cd ..
rm -rf ./*
```

It works, but just look at this script...

**Comment by mpluta-airhelp** [comment]
OK. Managed to streamline this a bit:
```
#!/bin/bash -x
PRID=$(expr "%teamcity.build.branch%" : '\([0-9]*\)\/merge')
if [ -z "$PRID" ]
then
  echo "Cannot run pronto analysis on non-PR branch. Information about PR ID not found."
  exit 0
fi

if [ -d ./%PROJECT_NAME% ]
then
    rm -rf ./%PROJECT_NAME% 2> /dev/null
fi

git clone git@github.com:AirHelp/%PROJECT_NAME%.git
pushd %PROJECT_NAME%
git fetch origin pull/$PRID/head:pronto
git checkout pronto
#rest of the script goes here
```
So we can close this issue for now :)

**Comment by mmozuras** [comment]
@mpluta-airhelp cool, glad you managed to work it out 😄
