### ISSUE TITLE
undefined method body for nil in Github pull request formatter

### ISSUE THREAD

**Issue by jhass** [mmozuras/pronto#171]
Probably a bug, at least improper error handling somewhere.
```
/var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/github.rb:35:in `create_pull_comment': undefined method `body' for nil:NilClass (NoMethodError)
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/formatter/pull_request_formatter.rb:14:in `block in submit_comments'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/formatter/pull_request_formatter.rb:14:in `each'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/formatter/pull_request_formatter.rb:14:in `submit_comments'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/formatter/git_formatter.rb:10:in `format'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto.rb:59:in `block in run'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto.rb:58:in `each'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto.rb:58:in `run'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/cli.rb:54:in `block in run'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/cli.rb:53:in `chdir'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/lib/pronto/cli.rb:53:in `run'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/gems/pronto-0.7.0/bin/pronto:6:in `<top (required)>'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/bin/pronto:23:in `load'
	from /var/lib/github-hook-receiver/.gem/ruby/2.2.4/bin/pronto:23:in `<main>'

**Comment by jhass** [comment]
Nvm, it looks like something ran in parallel, changing the working tree under the hood.
