### ISSUE TITLE
pronto does not compatible with thor 0.19.2

### ISSUE THREAD

**Issue by juno** [mmozuras/pronto#194]
pronto doesn't work with thor 0.19.2 which has released at Nov 26, 2016 (and it's 0.19.3 now).

```
Expected array default value for '--formatters'; got "text" (string)
/opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-0.19.3/lib/thor/base.rb:534:in `thor_reserved_word?': "run" is a Thor reserved word and cannot be defined as command (RuntimeError)
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-0.19.3/lib/thor/base.rb:597:in `method_added'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:44:in `<class:CLI>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:4:in `<module:Pronto>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:3:in `<top (required)>'
	from /opt/circleci/ruby/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/circleci/ruby/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/bin/pronto:4:in `<top (required)>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
       [ERROR] Couldn't execute pronto
```

Root cause is that thor 0.19.2 changed it's protected method name in [this](https://github.com/erikhuda/thor/commit/3e2dfe9d431758b2aa0996e304744881dc78825c#diff-ffcb86f580effa19deae13c3f3ec990f) commit.

- Before:
  - `Thor::Base.is_thor_reserved_word?`
- After:
  - `Thor::Base.thor_reserved_word?`

**Comment by juno** [comment]
Thor 0.19.4 has just released and it compatible with pronto.
https://github.com/erikhuda/thor/issues/534#issuecomment-263193920
