### ISSUE TITLE
GitLab integration doesn't work

### ISSUE THREAD

**Issue by sauliusgrigaitis** [mmozuras/pronto#219]
```
GITLAB_API_PRIVATE_TOKEN="..." GITLAB_API_ENDPOINT="..." bundle exec pronto run -f gitlab -c origin/develop
 ...
/home/saulius/.rvm/gems/ruby-2.4.1/gems/gitlab-3.7.0/lib/gitlab/request.rb:102:in `set_authorization_header': Please provide a private_token or auth_token for user (Gitlab::Error::MissingCredentials)
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/gitlab-3.7.0/lib/gitlab/request.rb:42:in `get'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/gitlab-3.7.0/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/gitlab.rb:11:in `commit_comments'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/formatter/commit_formatter.rb:6:in `each'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto.rb:59:in `block in run'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto.rb:58:in `each'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto.rb:58:in `run'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/cli.rb:54:in `block in run'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/cli.rb:53:in `chdir'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/lib/pronto/cli.rb:53:in `run'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/saulius/.rvm/gems/ruby-2.4.1/gems/pronto-0.8.2/bin/pronto:6:in `<top (required)>'
	from /home/saulius/.rvm/gems/ruby-2.4.1/bin/pronto:22:in `load'
	from /home/saulius/.rvm/gems/ruby-2.4.1/bin/pronto:22:in `<main>'
	from /home/saulius/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/saulius/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mmozuras** [comment]
@sauliusgrigaitis since [v0.8.0](https://github.com/mmozuras/pronto/releases/tag/v0.8.0), Pronto ENV config variables are prefixed with `PRONTO_` ([CHANGELOG](https://github.com/mmozuras/pronto/blob/master/CHANGELOG.md#080), [PR](https://github.com/mmozuras/pronto/pull/184)). So, for example: `PRONTO_GITLAB_API_PRIVATE_TOKEN` instead of `GITLAB_API_PRIVATE_TOKEN`.

Hope that it helps! 🙇

**Comment by sauliusgrigaitis** [comment]
Thanks. Informative message for old ENV variables users would be nice because in this community changelogs...

**Comment by mmozuras** [comment]
@sauliusgrigaitis good point! 😄 

For next release, I'll consider using something `post_install_message` from `Gem::Specification` to inform about these kind of changes.
