### ISSUE TITLE
Running Pronto on Pull requests coming from forked repos

### ISSUE THREAD

**Issue by tansaku** [mmozuras/pronto#88]
I'm trying to get pronto to submit comments on a pull request coming from a forked repo, but I can't seem to get anything to work:

```
[tansaku@Samuels-MBP:~/Documents/Github/MakersAcademy/airport_challenge (master)]$ 
→ PULL_REQUEST_ID=133 pronto run -f github_pr
0 Pronto messages posted to GitHub
```

Here's the pull request that I want to get commented: https://github.com/makersacademy/airport_challenge/pull/133

Having tried the above on the upstream repo (makersacademy/airport_challenge), I guessed (by repeatedly watching the animated gif) that I needed to be in the feature branch in order for things to work, so staying in my local repo that has makersacademy/airport_challenge as origin, I did the following:

```
$ git checkout -b tansaku/master # checkout the branch on the forked repo the pull request is coming from 
$ PULL_REQUEST_ID=133 pronto run -f github_pr
```

which gives this error:

```
/Users/tansaku/.rvm/gems/ruby-2.2.2/gems/octokit-3.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/pulls/133/comments: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/octokit-3.8.0/lib/octokit/client.rb:339:in `request'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/octokit-3.8.0/lib/octokit/client.rb:200:in `paginate'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/octokit-3.8.0/lib/octokit/client/pull_requests.rb:184:in `pull_request_comments'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/github.rb:11:in `pull_comments'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/formatter/github_pull_request_formatter.rb:31:in `create_comment'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/formatter/github_pull_request_formatter.rb:21:in `block in format'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/formatter/github_pull_request_formatter.rb:8:in `map'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/formatter/github_pull_request_formatter.rb:8:in `format'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto.rb:37:in `run'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/lib/pronto/cli.rb:52:in `run'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/gems/pronto-0.4.2/bin/pronto:6:in `<top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/bin/pronto:23:in `load'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/bin/pronto:23:in `<main>'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tansaku/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

which makes it look like the API endpoint is not configured properly for working with forks maybe?

`https://api.github.com/pulls/133/comments`

since that request should be for:

`https://api.github.com/repos/makersacademy/airport_challenge/pulls/133/comments`

Just for confirmation I can run pronto and get output locally:

```
$ pronto run
lib/airport.rb:6 W: Doesn't depend on instance state (UtilityFunction)
lib/plane.rb:5 I: Style/TrivialAccessors: Use `attr_reader` to define trivial reader methods. (https://github.com/bbatsov/ruby-style-guide#attr_family)
```

any thoughts?  Would love to be able to run pronto on pull requests from forked repos.

**Comment by giedriusr** [comment]
There is a new PR regarding forks: https://github.com/mmozuras/pronto/pull/86

**Comment by mmozuras** [comment]
This comment tells the story: https://github.com/mmozuras/pronto/pull/86#issuecomment-150963747

@tansaku thanks for bringing this up! :bow: :smile:
