### ISSUE TITLE
certificate verify failed (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by fabiosammy** [mmozuras/pronto#95]
When i need run pronto to my own gitlab with ssl self-signed, i get:
`/home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in connect: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)`

How i can workaround on this?

Stack trace
```
$ bundle exec pronto run -f gitlab -c origin/master
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /home/gitlab-runner/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/httparty-0.13.5/lib/httparty.rb:460:in `get'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/gitlab-3.4.0/lib/gitlab/request.rb:41:in `get'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/gitlab-3.4.0/lib/gitlab/client/repositories.rb:111:in `commit_comments'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/gitlab.rb:10:in `commit_comments'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/formatter/gitlab_formatter.rb:23:in `create_comment'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/formatter/gitlab_formatter.rb:9:in `block in format'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/formatter/gitlab_formatter.rb:8:in `map'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/formatter/gitlab_formatter.rb:8:in `format'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto.rb:37:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/lib/pronto/cli.rb:52:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/gems/pronto-0.4.2/bin/pronto:6:in `<top (required)>'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/bin/pronto:23:in `load'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/bin/pronto:23:in `<main>'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `eval'
	from /home/gitlab-runner/.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fabiosammy** [comment]
Sorry,my fault, following the trace again, the "gitlab" gem get this, so, in gitlab source gem, i see:
https://github.com/narkoz/gitlab#cli

Then i add env `GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"`, but it's only on new gitlab gem version, and not on 3.4.0.

:cry:

**Comment by mmozuras** [comment]
@fabiosammy do I understand correctly: this issue can be closed when next version of `gitlab` will be released with [this commit](https://github.com/NARKOZ/gitlab/commit/a2360f08019632c2660dbbc6753bd3094286b993)?

**Comment by fabiosammy** [comment]
yeap!

**Comment by mmozuras** [comment]
@fabiosammy as it's not a Pronto bug, closing this :smile:
